uek_demo_homepage:
    path:     /feeds
    defaults: { _controller: UekDemoBundle:Feed:index }

uek_demo_about_me:
    path:     /aboutme
    defaults: { _controller: UekDemoBundle:About:index }

uek_demo_services_hello:
    path: /services/hello
    defaults: { _controller: UekDemoBundle:Services:hello }
uek_demo_services_show_session:
    path: /services/show-session
    defaults: { _controller: UekDemoBundle:Services:showSession }