questionnaire:
    path:     /
    defaults: { _controller: "UekDemoBundle:Questionnaire:index" }

questionnaire_show:
    path:     /{id}/show
    defaults: { _controller: "UekDemoBundle:Questionnaire:show" }
    requirements:
        id: \d+

questionnaire_show_by_lastname:
    path:     /{lastname}/show
    defaults: { _controller: "UekDemoBundle:Questionnaire:showByLastname" }

questionnaire_new:
    path:     /new
    defaults: { _controller: "UekDemoBundle:Questionnaire:new" }

questionnaire_create:
    path:     /create
    defaults: { _controller: "UekDemoBundle:Questionnaire:create" }
    requirements: { _method: post }

questionnaire_edit:
    path:     /{id}/edit
    defaults: { _controller: "UekDemoBundle:Questionnaire:edit" }

questionnaire_update:
    path:     /{id}/update
    defaults: { _controller: "UekDemoBundle:Questionnaire:update" }
    requirements: { _method: post|put }

questionnaire_delete:
    path:     /{id}/delete
    defaults: { _controller: "UekDemoBundle:Questionnaire:delete" }
    requirements: { _method: post|delete }
